repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/PyCQA/autoflake
  rev: v2.1.1
  hooks:
  - id: autoflake

- repo: https://github.com/akaihola/darker
  rev: 1.7.2
  hooks:
    - id: darker

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.2.0
  hooks:
  - id: mypy
